### ISSUE TITLE
Allow generic drivers to construct datasets

### ISSUE THREAD

**Issue by Micky774** [quinngroup/CiliaRepresentation#1]
The generic driver should be able to create a PyTorch data set. These data sets will vary module-by-module and should be handled individually, however the generic driver should have uniform syntax and usage for whatever data sets it implements.

**Comment by AnonymousFool** [comment]
Decided against generic driver because PyTorch datasets have scope issues.
Returning datasets from functions causes pickling errors, rendering the datasets unusable for model training and testing.
Passing datasets to functions is untested.
