### ISSUE TITLE
Make torch dataset from synthetic dynamics data

### ISSUE THREAD

**Issue by AnonymousFool** [quinngroup/CiliaRepresentation#22]
Built off of a (observation #) x (time) x (latent space axes) shaped numpy array.
For example, a 1000 x 20 x 10 shape numpy array has 1000 time series formed of 20 time steps with 10 latent space variables.
Define a torch dataset class (a la those in the Datasets.py file) that allows for getting each time series observation as a torch tensor.

**Comment by alexeldridge** [comment]
created at dynamics/datasets/Datasets.py
