### ISSUE TITLE
Exp11: NVP vs NVP_1

### ISSUE THREAD

**Issue by Micky774** [quinngroup/CiliaRepresentation#27]
Using the most recent NVP (updated default parameters) compare against NVP_1. Proposed testing over 30 epochs each.

**Comment by idhumphrey** [comment]
Going to test NVP and NVP_1 over 30 epochs.

**Comment by idhumphrey** [comment]
Script written and ready to be run.

**Comment by idhumphrey** [comment]
Running the script.

**Comment by idhumphrey** [comment]
Upon inspection, NVP_1 has a lower floor of convergence and displays better degree of recreation than NVP.  Recommend adopting NVP_1 as default model. (Meekail and Quinn agree.)
