### ISSUE TITLE
Exp1: Learning Rate Stability Test

### ISSUE THREAD

**Issue by AnonymousFool** [quinngroup/CiliaRepresentation#4]
Need to test stability of different learning rates on NVP.py

**Comment by AnonymousFool** [comment]
Going to test learning rates of powers of ten from 1e-3 to 1e-8.

**Comment by AnonymousFool** [comment]
Script written and ready to be run.

**Comment by Micky774** [comment]
Trial completed and results saved

**Comment by Micky774** [comment]
For major learning rate, 1e-3 is the upper bound for stable learning. Safe learning rates range from 1e-4 to 1e-6. Suggested usage: default 1e-4 if using learning rate scheduling, else default to 1e-5
