### ISSUE TITLE
Convert UCR files to Pytorch Tensors

### ISSUE THREAD

**Issue by nssafir** [quinngroup/CiliaRepresentation#47]
Write Python script to convert .ts files from UCR dataset to numpy arrays

**Comment by Micky774** [comment]
Instead of PyTorch tensors you'll be saving them as numpy arrays (.npy) right? That's how the appearance dataset is currently set up

**Comment by nssafir** [comment]
Yes, my bad

**Comment by alexeldridge** [comment]
The numpy array formatted data is in the same folders as the original .ts files, and they are stored as 2nd order numpy arrays with shape (dataset_size, dimension) with entries that are pandas series objects with length (time_series_length).
To accomplish this I ran the script ts_to_npy.py in /local_data/timeseries/Multivariate_ts/ on logan
