### ISSUE TITLE
Exp3: Pseudo learning rate

### ISSUE THREAD

**Issue by Micky774** [quinngroup/CiliaRepresentation#6]
Test various learning rates for the pseudoinputs using the new default batch size/learning rate values provided by experiments 1 (#4) and 2 (#5).

**Comment by idhumphrey** [comment]
Adopting a default learning rate of 1e-5 and a default batch size of 160, we will test learning rates for the pseudoinputs: {1e-5, 7e-6, 4e-6, 1e-6, 7e-7, 4e-7, 1e-7} over 30 epochs each.

**Comment by idhumphrey** [comment]
Script has been written and is ready to be run.

**Comment by idhumphrey** [comment]
Found a pseudo learning rate of 4e-7 to be ideal. Meekail agrees.
