### ISSUE TITLE
Exp4: Weight Decay

### ISSUE THREAD

**Issue by Micky774** [quinngroup/CiliaRepresentation#7]
Test out various weight decay values and their effects on rate of convergence and loss stability

**Comment by idhumphrey** [comment]
We will test the L2 weight decay values: {1e-7, 1e-6, 1e-5, 1e-4, 1e-3} over 30 epochs.

**Comment by idhumphrey** [comment]
Script written and ready to be run.

**Comment by Micky774** [comment]
Updated experiment to set batch-size to 160 over 2 GPU's. Currently running.

**Comment by idhumphrey** [comment]
Concluded that 1e-3 should be used as it has a higher variance, but it has lower minima. (Meekail agrees.)
